# Nama workflow
name: Generate GitHub Snake

# Kontrol kapan workflow berjalan
on:
  schedule:
    # Berjalan setiap hari pada jam 00:00 UTC
    - cron: "0 0 * * *"
  # Tombol untuk menjalankan workflow secara manual dari tab Actions
  workflow_dispatch:

jobs:
  build:
    # ==========================================================
    # BAGIAN 1: KUNCI PERBAIKAN UNTUK ERROR 403 (IZIN)
    # ==========================================================
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark